export const enum ConfigKey {
    PORT = "PORT",
    PIXEL_COUNT = "PIXEL_COUNT",
    DEFAULT_BRIGHTNESS = "DEFAULT_BRIGHTNESS",
    DEFAULT_EFFECT = "DEFAULT_EFFECT",
    LUXSRV_ADDRESS = "LUXSRV_ADDRESS",
}
